### ISSUE TITLE
Get readings from the gyroscope

### ISSUE THREAD

**Issue by MarcusAronsson1** [DIT112-V19/group-02#20]
## User Story
As a SafeSweeper operator I want to know in which direction the car is pointing so that I know where its going to go.

## Acceptance criteria
- [x] Gyroscope is connected to car.
- [x] Serial monitor prints readings from the gyroscope.

#### Steps to reproduce the behavior:
* Start the car.
* Check if the serial monitor shows readings from the gyroscope.

**Comment by platisd** [comment]
Looks great! However please use the term "Acceptance criteria" as the definition of done refers to something else (specifically "when you consider any story done").
