### ISSUE TITLE
Firmly solder RFID scanner onto the car.

### ISSUE THREAD

**Issue by Middlo** [DIT112-V19/group-02#36]
## User Story
As a SafeSweeper operator, I want to be reinforced that the RFID module will be soldered in place to ensure that even in the roughest conditions the reader won't fall off.

## Acceptance criteria

- [ ] RFID module won't drop whilst car is moving
- [ ] RFID module can't be removed with finger force
- [ ] RFID module won't fall off when car is dropped from small height

#### Steps to reproduce the behavior:
* Try to remove RFID by pulling it off with bare fingers
* Drop the car from an appropriate height of 10cm
* Drive the car around

**Comment by platisd** [comment]
Please don't attach anything permanently to the car or try to drop it from any height :rofl:

**Comment by MarcusAronsson1** [comment]
We're not allowed to solder on the car.

**Comment by platisd** [comment]
Well, you're not allowed to solder **on** the car, however keep in mind that there's the PCB design workshop coming up next, which will give you the chance to create your own board where you can solder whatever you want on it! So perhaps you can think of a smart way to connect things steadily with a board of your own creation, up to 10*10cm in size. 

PS. You wouldn't be able to solder anything on the car anyway as it's made from plastic. :stuck_out_tongue:
