### ISSUE TITLE
Improve the UI of the mobile application

### ISSUE THREAD

**Issue by Middlo** [DIT112-V19/group-02#37]
## User Story
As a SafeSweeper operator, I want the application's UI to be aesthetically pleasing so that it is easy to understand.

## Acceptance criteria

- [ ] UI must be clear and understandable
- [ ] UI should not be too cluttered

#### Steps to reproduce the behavior:

* Start the application
* Use the application
* Application should run smoothly and be well designed for the intended user

**Comment by eyuell** [comment]
This issue is too generic and we have created specific issues for sprint 7. We agreed to close as it already helped us enough to reach to the specific issues.
