### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by MarcusAronsson1** [DIT112-V19/group-02#62]
## User Story
As a SafeSweeper operator I want the software to be properly tested so that I can be sure that the product operates as it's supposed to. 

## Acceptance criteria
- [x] Travis is running
- [x] Travis gives you a result

#### Steps to reproduce the behavior:
* Go to Github and create a pull request

**Comment by MarcusAronsson1** [comment]
@platisd 
How do I add libraries so they are used by Travis. We use RFID.h and TinyGPS.h in our .ino and I don't know how to edit the .travis.yml file to find those files. 

I'm trying to find out about this online but  it's pretty hard overall to find help about Travis it seems.

**Comment by platisd** [comment]
Are they installable via the Arduino IDE library manager? If yes then write their titles, separated by commas I believe, after:
```
    - arduino --install-library "Smartcar shield"
```
If they are not, I *think* that if you `git clone` them into the root of your repository, during the `install` phase, they will be picked up and used for the sketch compilation. Let me know how it goes and I can have a look later if you don't get it working.

**Comment by MarcusAronsson1** [comment]
Yea forgot that part, they are **not** installable through the library manager. 
I will continue looking but I feel somewhat stuck at the moment.

Thanks!

**Comment by platisd** [comment]
Assuming that I guessed which libraries you are using correctly, try to add the following lines in the `install` step of your `.travis.yml`:
```yml
- git clone git@github.com:mikalhart/TinyGPS.git
- git clone git@github.com:song940/RFID-RC522.git
```

**Comment by MarcusAronsson1** [comment]
Error: The command "git clone git@github.com:mikalhart/TinyGPS.git" failed and exited with 128 during .
Permission denied.

**Comment by platisd** [comment]
Use the `https` versions instead:
```yml
- git clone https://github.com/mikalhart/TinyGPS.git
- git clone https://github.com/song940/RFID-RC522.git
```

**Comment by MarcusAronsson1** [comment]
It looks like it clones the repos now but it still gives error.
`SafeSweeper:3:18: error: RFID.h: No such file or directory`

**Comment by platisd** [comment]
Can you provide a link to the failed job?

**Comment by MarcusAronsson1** [comment]
https://travis-ci.org/DIT112-V19/group-02/jobs/528813828

**Comment by platisd** [comment]
Try this then:
```yml
- git clone https://github.com/mikalhart/TinyGPS.git $HOME/arduino_ide/libraries/TinyGPS
- git clone https://github.com/song940/RFID-RC522.git $HOME/arduino_ide/libraries/RFID-RC522
```

**Comment by MarcusAronsson1** [comment]
IT'S WORKING!

**Comment by MarcusAronsson1** [comment]
Thanks a lot for all the help! @platisd
