### ISSUE TITLE
Make a 3D-model of the car chassi

### ISSUE THREAD

**Issue by malties** [DIT112-V19/group-02#7]
# User Story
As a SafeSweeper operator, I want a 3D-model of the car so that I can see what the chassi will look like.
# Acceptance criteria
- [x] 3D-model can be viewed on GitHub

**Comment by Middlo** [comment]
![CasePrototype](https://user-images.githubusercontent.com/43146257/55902555-137e2180-5bcc-11e9-9718-13350fdb300d.png)
