### ISSUE TITLE
CI error cloning submodule

### ISSUE THREAD

**Issue by MarcusAronsson1** [DIT112-V19/group-02#76]
## Related issues
#62 

## Description
Travis does not finish the test since the submodules it requires are not properly imported

## Acceptance criteria

- [x] TinyGPS library properly imported during Travis test

#### Steps to reproduce the behavior:
* Create pull request
* Let Travis run

**Comment by MarcusAronsson1** [comment]
Error when @malties makes a pull request.
```
$ git clone git@github.com:mikalhart/TinyGPS.git
Cloning into 'TinyGPS'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

The command "git clone git@github.com:mikalhart/TinyGPS.git" failed and exited with 128 during .
```

Weird since the repository is public and it works when I create pull requests.

Do you know anything about this @platisd ?

**Comment by platisd** [comment]
I don't think this ever worked. :smiley: 
Use `git clone https://github.com/mikalhart/TinyGPS.git` instead.

**Comment by platisd** [comment]
But wait a minute, is @malties based off of an older branch perhaps? Your latest `master` has the correct `git clone` command. Which pull request is that?

**Comment by MarcusAronsson1** [comment]
Yea it looks like this in the travis.yml
`- git clone https://github.com/mikalhart/TinyGPS.git $HOME/arduino_ide/libraries/TinyGPS`

**Comment by MarcusAronsson1** [comment]
Oh damn, apparently her build config is an older one. I thought Travis was running with the config currently in master. How does it work then? Surely it doesn't use the local .travis.yml on @malties computer?

**Comment by platisd** [comment]
Yeah, it looks like this **now**. But how does it look on the pull request you're trying?

**Comment by platisd** [comment]
Travis runs two jobs by default. One on "your branch" no matter how old it is and one "on the master" if you understand what I mean. For example, you can see how #86 fails when building "on your (old) branch" but works when it builds against the `master`. This means that you should either rebase your branch according to the latest `master` or merge `master` into your branch.

**Comment by MarcusAronsson1** [comment]
Ah! It makes sense now.
It tries the branch you're making the pull request from (with the config in that branch).
And it also tries if the master is passing if the pull request would have been merged (with the config in master).
Is this correct? Then the new branches we create from now on should work on both points, and the older branches should only work on the "master" test.

**Comment by platisd** [comment]
> It tries the branch you're making the pull request from (with the config in that branch).
> And it also tries if the master is passing if the pull request would have been merged (with the config in master).

That is exactly what it does! :+1:
