### ISSUE TITLE
Hardcoded TravisCI $HOME directory in .travis.yml

### ISSUE THREAD

**Issue by platisd** [DIT112-V19/group-02#94]
Your `.travis.yml` contains a [hardcoded path](https://github.com/DIT112-V19/group-02/blob/master/.travis.yml#L51-L52) to the TravisCI `$HOME` directory.

Please use the `$HOME` variable instead of `/home/travis` to ensure this will always be built irrespective of what username `TravisCI` chooses to have.

**Comment by MarcusAronsson1** [comment]
I'll fix this.
